apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-gitops-app
  namespace: training

spec:
  replicas: 2

  selector:
    matchLabels:
      app: python-gitops-app

  template:
    metadata:
      labels:
        app: python-gitops-app

    spec:
      containers:
        - name: python-gitops-app
          image: 386757865964.dkr.ecr.us-east-1.amazonaws.com/sunil-python-gitops-app
          ports:
            - containerPort: 5000
