apiVersion: v1
kind: Service
metadata:
  name: python-gitops-app
  namespace: training

spec:
  type: ClusterIP

  selector:
    app: python-gitops-app

  ports:
    - port: 80
      targetPort: 5000
