apiVersion: v1
kind: Namespace
metadata:
  name: day17
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunil-ecr-app
  namespace: day17
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sunil-ecr-app
  template:
    metadata:
      labels:
        app: sunil-ecr-app
    spec:
      containers:
        - name: sunil-ecr-container
          image: 386757865964.dkr.ecr.us-east-1.amazonaws.com/sunil-ecr:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
